### For Data Exploration - Just change target col to get subset

In [1]:
TARGET_COL = "type"

In [2]:
from api311 import Year

old = Year("data/cleaned2015.csv")
new = Year("data/cleaned2025.csv")
old.make_points()
new.make_points()

old_summary_dct = old.summarize(TARGET_COL)
new_summary_dct = new.summarize(TARGET_COL)

In [3]:
print( old_summary_dct["counts"])
new_monthly_data = new_summary_dct["monthly"]

type
Request for Snow Plowing                       30346
Missed Trash/Recycling/Yard Waste/Bulk Item    16408
Request for Pothole Repair                      8111
Street Light Outages                            7636
Pothole Repair (Internal)                       5393
                                               ...
Test Case A                                        1
Automotive Noise Disturbance                       1
Schedule a Bulk Item Pickup SS                     1
Street Light Longterm Repair                       1
Hero Square Sign Request                           1
Name: count, Length: 148, dtype: int64

In [4]:
new_monthly_data

,January,February,March,April,May,June,July,August,September,October,November,December
type,,,,,,,,,,,,
Abandoned Building,0.0,0.0,1.0,3.0,11.0,9.0,13.0,10.0,7.0,7.0,6.0,4.0
Automotive Noise Disturbance,3.0,1.0,3.0,6.0,1.0,0.0,2.0,0.0,2.0,0.0,3.0,0.0
BWSC General Request,25.0,27.0,20.0,13.0,21.0,15.0,35.0,22.0,29.0,35.0,32.0,31.0
BWSC Pothole,1.0,7.0,12.0,17.0,10.0,7.0,7.0,8.0,7.0,7.0,4.0,3.0
Bed Bugs,4.0,1.0,3.0,4.0,2.0,1.0,3.0,3.0,3.0,3.0,8.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Walk-In Service Inquiry,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Work Hours-Loud Noise Complaints,7.0,10.0,4.0,5.0,12.0,13.0,17.0,19.0,18.0,24.0,14.0,5.0
Work w/out Permit,52.0,28.0,43.0,71.0,58.0,40.0,38.0,36.0,24.0,69.0,69.0,71.0
Working Beyond Hours,44.0,29.0,39.0,52.0,52.0,37.0,25.0,25.0,32.0,42.0,61.0,55.0
Zoning,2.0,2.0,0.0,2.0,0.0,0.0,0.0,4.0,0.0,3.0,4.0,4.0

In [5]:
old.get_subset("neighborhood", ["Roxbury", "Back Bay"], cache=True)["neighborhood"]

0         Back Bay
3          Roxbury
14        Back Bay
15        Back Bay
16        Back Bay
            ...
121031    Back Bay
121034     Roxbury
121049     Roxbury
121057    Back Bay
121062    Back Bay
Name: neighborhood, Length: 16871, dtype: object

## Shapefile Exploration

In [7]:
import geopandas as gpd

fp = "data/neighborhood_shapes/Boston_Neighborhood_Boundaries.shp"
gdf = gpd.read_file(fp)
gdf

,name,acres,neighborho,sqmiles,Shape_Leng,Shape_Area,shape_wkt,geometry
0,Roslindale,1605.568237,15,2.51,0.169120,0.000709,None,"MULTIPOLYGON (((-71.12593 42.272, -71.12575 42..."
1,Jamaica Plain,2519.245394,11,3.94,0.179578,0.001113,None,"POLYGON ((-71.10499 42.32609, -71.10488 42.326..."
2,Mission Hill,350.853564,13,0.55,0.059235,0.000155,None,"POLYGON ((-71.09043 42.33576, -71.09275 42.333..."
3,Longwood,188.611947,28,0.29,0.038816,0.000083,None,"POLYGON ((-71.09811 42.33672, -71.09892 42.336..."
4,Bay Village,26.539839,33,0.04,0.015625,0.000012,None,"POLYGON ((-71.06663 42.34877, -71.06739 42.348..."
5,Leather District,15.639908,27,0.02,0.010478,0.000007,None,"POLYGON ((-71.05838 42.34982, -71.05877 42.349..."
6,Chinatown,76.324410,26,0.12,0.032741,0.000034,None,"POLYGON ((-71.0579 42.35237, -71.05796 42.3523..."
7,North End,126.910439,14,0.20,0.052807,0.000056,None,"POLYGON ((-71.05199 42.36883, -71.05169 42.368..."
8,Roxbury,2108.469072,16,3.29,0.153269,0.000932,None,"POLYGON ((-71.09646 42.29322, -71.09662 42.293..."
9,South End,471.535356,32,0.74,0.058465,0.000208,None,"POLYGON ((-71.06834 42.34774, -71.06834 42.347..."
10,Back Bay,399.314411,2,0.62,0.063374,0.000177,None,"POLYGON ((-71.07569 42.35691, -71.07579 42.356..."
11,East Boston,3012.059593,8,4.71,0.394692,0.001334,None,"POLYGON ((-70.99546 42.39393, -70.99524 42.393..."
12,Charlestown,871.541223,4,1.36,0.186462,0.000386,None,"MULTIPOLYGON (((-71.07416 42.3905, -71.07415 4..."
13,West End,190.490732,31,0.30,0.059143,0.000084,None,"MULTIPOLYGON (((-71.06478 42.36881, -71.06467 ..."
14,Beacon Hill,200.156904,30,0.31,0.045895,0.000089,None,"POLYGON ((-71.07141 42.36118, -71.0708 42.3611..."
15,Downtown,397.472846,7,0.62,0.112374,0.000176,None,"POLYGON ((-71.05342 42.36129, -71.05275 42.360..."
16,Fenway,560.618461,34,0.88,0.081385,0.000248,None,"POLYGON ((-71.11011 42.35207, -71.10986 42.352..."
17,Brighton,1840.408596,25,2.88,0.158172,0.000814,None,"POLYGON ((-71.13517 42.34601, -71.13528 42.345..."
18,West Roxbury,3516.421786,19,5.49,0.212543,0.001553,None,"POLYGON ((-71.1647 42.30383, -71.15211 42.2945..."
19,Hyde Park,2927.221168,10,4.57,0.209005,0.001292,None,"POLYGON ((-71.12588 42.2721, -71.12577 42.2723..."
20,Mattapan,1352.098354,12,2.11,0.137579,0.000597,None,"POLYGON ((-71.09633 42.29316, -71.0962 42.2929..."
21,Dorchester,4662.879457,6,7.29,0.333581,0.002060,None,"MULTIPOLYGON (((-71.05895 42.32875, -71.05812 ..."
22,South Boston Waterfront,621.843524,29,0.97,0.125951,0.000275,None,"POLYGON ((-71.04348 42.35293, -71.04347 42.352..."
23,South Boston,1439.888807,17,2.25,0.212399,0.000637,None,"POLYGON ((-71.06104 42.34282, -71.06089 42.342..."
24,Allston,998.534479,24,1.56,0.122311,0.000442,None,"POLYGON ((-71.13517 42.34601, -71.13823 42.347..."
25,Harbor Islands,824.888658,22,1.29,0.297931,0.000365,None,"MULTIPOLYGON (((-70.96718 42.31376, -70.96771 ..."