### For Data Exploration - Just change target col to get subset

In [1]:
AREA_COL = "neighborhood"
TARGET_COL = "type"

In [ ]:
from api311 import Year

old = Year("data/cleaned2015.csv")
new = Year("data/cleaned2025.csv")
old.make_points()
new.make_points()

old_summary_dct = old.summarize(category_col=AREA_COL, target_col=TARGET_COL)

new_summary_dct = new.summarize(category_col=AREA_COL, target_col=TARGET_COL)

In [3]:
sig15 = old_summary_dct['signatures']
sig25 = new_summary_dct['signatures']

In [5]:
new_summary_dct["monthly"]

,January,February,March,April,May,June,July,August,September,October,November,December
type,,,,,,,,,,,,
Abandoned Building,0.0,0.0,1.0,3.0,11.0,9.0,13.0,10.0,7.0,7.0,6.0,4.0
Automotive Noise Disturbance,3.0,1.0,3.0,6.0,1.0,0.0,2.0,0.0,2.0,0.0,3.0,0.0
BWSC General Request,25.0,27.0,20.0,13.0,21.0,15.0,35.0,22.0,29.0,35.0,32.0,31.0
BWSC Pothole,1.0,7.0,12.0,17.0,10.0,7.0,7.0,8.0,7.0,7.0,4.0,3.0
Bed Bugs,4.0,1.0,3.0,4.0,2.0,1.0,3.0,3.0,3.0,3.0,8.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Walk-In Service Inquiry,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Work Hours-Loud Noise Complaints,7.0,10.0,4.0,5.0,12.0,13.0,17.0,19.0,18.0,24.0,14.0,5.0
Work w/out Permit,52.0,28.0,43.0,71.0,58.0,40.0,38.0,36.0,24.0,69.0,69.0,71.0
Working Beyond Hours,44.0,29.0,39.0,52.0,52.0,37.0,25.0,25.0,32.0,42.0,61.0,55.0
Zoning,2.0,2.0,0.0,2.0,0.0,0.0,0.0,4.0,0.0,3.0,4.0,4.0

In [4]:
sig15

type,Abandoned Building,Automotive Noise Disturbance,BWSC General Request,BWSC Pothole,Bed Bugs,Bicycle Issues,Billing Complaint,Breathe Easy,Bridge Maintenance,Building Inspection Request,...,Utility Call-In,Utility Casting Repair,Valet Parking Problems,Walk-In Service Inquiry,Water in Gas - High Priority,Watermain Break,Work Hours-Loud Noise Complaints,Work w/out Permit,Working Beyond Hours,Zoning
neighborhood,,,,,,,,,,,,,,,,,,,,,
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002946,0.000000,0.000884,...,0.000000,0.000000,0.000295,0.001178,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Allston,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.062992,...,0.011811,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.003937,0.000000
Allston / Brighton,0.000407,0.000000,0.002033,0.000000,0.003117,0.000678,0.000000,0.000678,0.000000,0.031843,...,0.003930,0.000813,0.000000,0.000000,0.000000,0.000542,0.001491,0.008401,0.001355,0.000407
Back Bay,0.000000,0.000000,0.001280,0.000366,0.000549,0.001097,0.000000,0.000000,0.000000,0.064192,...,0.005304,0.000366,0.000183,0.000000,0.000000,0.000000,0.002012,0.008413,0.006767,0.000183
Beacon Hill,0.000000,0.000000,0.000965,0.000000,0.000241,0.002413,0.000000,0.000000,0.000000,0.028958,...,0.004826,0.000241,0.000000,0.000000,0.000000,0.000241,0.002654,0.007239,0.004102,0.000241
Boston,0.000503,0.000000,0.002011,0.000503,0.000251,0.003016,0.000000,0.000251,0.000000,0.110581,...,0.005529,0.001508,0.000251,0.000000,0.000000,0.000251,0.003770,0.003770,0.007288,0.000251
Brighton,0.000000,0.000000,0.000000,0.000000,0.001605,0.003210,0.000000,0.000000,0.000000,0.051364,...,0.011236,0.000000,0.000000,0.000000,0.000000,0.001605,0.001605,0.006421,0.000000,0.001605
Charlestown,0.001476,0.000000,0.001230,0.000000,0.000984,0.000246,0.000000,0.000984,0.000492,0.039606,...,0.002214,0.000738,0.000000,0.000000,0.000000,0.000738,0.002706,0.009840,0.005166,0.000000
Dorchester,0.001593,0.000000,0.001593,0.000228,0.001138,0.000057,0.000171,0.001195,0.000057,0.038626,...,0.006201,0.001195,0.000000,0.000000,0.000000,0.001024,0.000853,0.011150,0.002048,0.000683
Downtown / Financial District,0.000298,0.000000,0.002984,0.000448,0.000448,0.002238,0.000149,0.000000,0.000149,0.071162,...,0.005967,0.001492,0.000000,0.000000,0.000000,0.001641,0.004625,0.005222,0.005371,0.000597
East Boston,0.002350,0.000000,0.003917,0.000000,0.002664,0.000157,0.000000,0.003447,0.000000,0.039799,...,0.004231,0.001097,0.000000,0.000000,0.000000,0.001410,0.001410,0.014259,0.003447,0.000627
Fenway / Kenmore / Audubon Circle / Longwood,0.000000,0.000000,0.000932,0.000000,0.002796,0.000932,0.000000,0.000000,0.000000,0.041007,...,0.007922,0.000932,0.000000,0.000000,0.000000,0.000932,0.000932,0.003262,0.003262,0.000466
Greater Mattapan,0.002221,0.000000,0.001709,0.000000,0.001025,0.000000,0.000171,0.003588,0.000000,0.024090,...,0.005296,0.001367,0.000000,0.000000,0.000000,0.000171,0.000342,0.008884,0.001196,0.000171
Hyde Park,0.003381,0.000000,0.000483,0.000483,0.001449,0.000161,0.000483,0.000322,0.000000,0.033162,...,0.005151,0.000161,0.000000,0.000000,0.000000,0.000161,0.000805,0.007244,0.000966,0.001127
Jamaica Plain,0.000933,0.000000,0.000699,0.000466,0.001166,0.000816,0.000117,0.001166,0.000000,0.042201,...,0.003497,0.000117,0.000000,0.000000,0.000000,0.000933,0.001049,0.006878,0.002565,0.000933
Mattapan,0.003279,0.000000,0.000000,0.000000,0.006557,0.000000,0.000000,0.000000,0.000000,0.042623,...,0.006557,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.009836,0.000000,0.003279
Mission Hill,0.001444,0.000000,0.002406,0.000481,0.009625,0.000000,0.000000,0.003369,0.000000,0.025505,...,0.008662,0.000481,0.000000,0.000000,0.000000,0.000962,0.001444,0.010587,0.003369,0.000481
Roslindale,0.002129,0.000000,0.002342,0.000000,0.000213,0.000213,0.000000,0.002555,0.000000,0.036414,...,0.005537,0.001065,0.000000,0.000000,0.000000,0.000213,0.000639,0.009370,0.001491,0.000213
Roxbury,0.001491,0.000000,0.001929,0.000351,0.002894,0.000438,0.000175,0.004823,0.000000,0.020872,...,0.005788,0.000438,0.000000,0.000000,0.000000,0.000965,0.001754,0.006139,0.001666,0.000526
South Boston,0.007034,0.000000,0.004689,0.000000,0.001172,0.000000,0.000000,0.008206,0.000000,0.044549,...,0.009379,0.000000,0.000000,0.000000,0.000000,0.001172,0.005862,0.030481,0.023447,0.002345
South Boston / South Boston Waterfront,0.001067,0.000000,0.001677,0.000457,0.000000,0.000457,0.000152,0.001372,0.000610,0.049855,...,0.008081,0.000305,0.000152,0.000000,0.000000,0.000457,0.003507,0.021955,0.008385,0.001067
South End,0.000176,0.000176,0.001409,0.000528,0.000528,0.000528,0.000000,0.000352,0.000000,0.043846,...,0.005459,0.001409,0.000000,0.000000,0.000000,0.000704,0.002289,0.012326,0.004754,0.000528
West Roxbury,0.001361,0.000000,0.001209,0.000151,0.000000,0.000000,0.000151,0.000302,0.000000,0.040363,...,0.004989,0.000605,0.000000,0.000000,0.000302,0.000605,0.001058,0.008163,0.001965,0.000605

## Shapefile Exploration

In [7]:
import geopandas as gpd

fp = "data/neighborhood_shapes/Boston_Neighborhood_Boundaries.shp"
gdf = gpd.read_file(fp)
gdf

,name,acres,neighborho,sqmiles,Shape_Leng,Shape_Area,shape_wkt,geometry
0,Roslindale,1605.568237,15,2.51,0.169120,0.000709,None,"MULTIPOLYGON (((-71.12593 42.272, -71.12575 42..."
1,Jamaica Plain,2519.245394,11,3.94,0.179578,0.001113,None,"POLYGON ((-71.10499 42.32609, -71.10488 42.326..."
2,Mission Hill,350.853564,13,0.55,0.059235,0.000155,None,"POLYGON ((-71.09043 42.33576, -71.09275 42.333..."
3,Longwood,188.611947,28,0.29,0.038816,0.000083,None,"POLYGON ((-71.09811 42.33672, -71.09892 42.336..."
4,Bay Village,26.539839,33,0.04,0.015625,0.000012,None,"POLYGON ((-71.06663 42.34877, -71.06739 42.348..."
5,Leather District,15.639908,27,0.02,0.010478,0.000007,None,"POLYGON ((-71.05838 42.34982, -71.05877 42.349..."
6,Chinatown,76.324410,26,0.12,0.032741,0.000034,None,"POLYGON ((-71.0579 42.35237, -71.05796 42.3523..."
7,North End,126.910439,14,0.20,0.052807,0.000056,None,"POLYGON ((-71.05199 42.36883, -71.05169 42.368..."
8,Roxbury,2108.469072,16,3.29,0.153269,0.000932,None,"POLYGON ((-71.09646 42.29322, -71.09662 42.293..."
9,South End,471.535356,32,0.74,0.058465,0.000208,None,"POLYGON ((-71.06834 42.34774, -71.06834 42.347..."
10,Back Bay,399.314411,2,0.62,0.063374,0.000177,None,"POLYGON ((-71.07569 42.35691, -71.07579 42.356..."
11,East Boston,3012.059593,8,4.71,0.394692,0.001334,None,"POLYGON ((-70.99546 42.39393, -70.99524 42.393..."
12,Charlestown,871.541223,4,1.36,0.186462,0.000386,None,"MULTIPOLYGON (((-71.07416 42.3905, -71.07415 4..."
13,West End,190.490732,31,0.30,0.059143,0.000084,None,"MULTIPOLYGON (((-71.06478 42.36881, -71.06467 ..."
14,Beacon Hill,200.156904,30,0.31,0.045895,0.000089,None,"POLYGON ((-71.07141 42.36118, -71.0708 42.3611..."
15,Downtown,397.472846,7,0.62,0.112374,0.000176,None,"POLYGON ((-71.05342 42.36129, -71.05275 42.360..."
16,Fenway,560.618461,34,0.88,0.081385,0.000248,None,"POLYGON ((-71.11011 42.35207, -71.10986 42.352..."
17,Brighton,1840.408596,25,2.88,0.158172,0.000814,None,"POLYGON ((-71.13517 42.34601, -71.13528 42.345..."
18,West Roxbury,3516.421786,19,5.49,0.212543,0.001553,None,"POLYGON ((-71.1647 42.30383, -71.15211 42.2945..."
19,Hyde Park,2927.221168,10,4.57,0.209005,0.001292,None,"POLYGON ((-71.12588 42.2721, -71.12577 42.2723..."
20,Mattapan,1352.098354,12,2.11,0.137579,0.000597,None,"POLYGON ((-71.09633 42.29316, -71.0962 42.2929..."
21,Dorchester,4662.879457,6,7.29,0.333581,0.002060,None,"MULTIPOLYGON (((-71.05895 42.32875, -71.05812 ..."
22,South Boston Waterfront,621.843524,29,0.97,0.125951,0.000275,None,"POLYGON ((-71.04348 42.35293, -71.04347 42.352..."
23,South Boston,1439.888807,17,2.25,0.212399,0.000637,None,"POLYGON ((-71.06104 42.34282, -71.06089 42.342..."
24,Allston,998.534479,24,1.56,0.122311,0.000442,None,"POLYGON ((-71.13517 42.34601, -71.13823 42.347..."
25,Harbor Islands,824.888658,22,1.29,0.297931,0.000365,None,"MULTIPOLYGON (((-70.96718 42.31376, -70.96771 ..."