### For Data Exploration - Just change target col to get subset

In [24]:
TARGET_COL = "type"

In [25]:
from api311 import Year

old = Year("data/cleaned2015.csv")
new = Year("data/cleaned2025.csv")
old.make_points()
new.make_points()

old_summary_dct = old.summarize(TARGET_COL)
new_summary_dct = new.summarize(TARGET_COL)

/Users/ian/Desktop/MAINFRAME/School/Year 3/Year3Sem2/DS4200/DS4200_GroupProject/api311.py:11: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  self.data = pd.read_csv(fp)

In [26]:
old_monthly_data = old_summary_dct["monthly"]
new_monthly_data = new_summary_dct["monthly"]

In [27]:
old_monthly_data

,January,February,March,April,May,June,July,August,September,October,November,December
type,,,,,,,,,,,,
Abandoned Building,5.0,2.0,9.0,19.0,14.0,18.0,15.0,21.0,23.0,12.0,10.0,4.0
Automotive Noise Disturbance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
BWSC General Request,19.0,9.0,11.0,12.0,19.0,12.0,12.0,35.0,32.0,19.0,10.0,12.0
BWSC Pothole,1.0,4.0,3.0,2.0,5.0,4.0,3.0,5.0,2.0,1.0,0.0,0.0
Bed Bugs,4.0,2.0,36.0,6.0,8.0,17.0,17.0,31.0,14.0,11.0,8.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Watermain Break,5.0,6.0,6.0,9.0,11.0,11.0,6.0,13.0,5.0,6.0,3.0,5.0
Work Hours-Loud Noise Complaints,11.0,4.0,13.0,9.0,22.0,18.0,11.0,27.0,29.0,28.0,19.0,16.0
Work w/out Permit,67.0,39.0,68.0,81.0,129.0,127.0,87.0,103.0,109.0,103.0,123.0,80.0
Working Beyond Hours,17.0,19.0,17.0,39.0,35.0,36.0,29.0,30.0,56.0,53.0,44.0,25.0
Zoning,4.0,6.0,2.0,8.0,6.0,7.0,8.0,14.0,4.0,3.0,2.0,5.0

In [28]:
new_monthly_data

,January,February,March,April,May,June,July,August,September,October,November,December
type,,,,,,,,,,,,
Abandoned Building,0.0,0.0,1.0,3.0,11.0,9.0,13.0,10.0,7.0,7.0,6.0,4.0
Automotive Noise Disturbance,3.0,1.0,3.0,6.0,1.0,0.0,2.0,0.0,2.0,0.0,3.0,0.0
BWSC General Request,25.0,27.0,20.0,13.0,21.0,15.0,35.0,22.0,29.0,35.0,32.0,31.0
BWSC Pothole,1.0,7.0,12.0,17.0,10.0,7.0,7.0,8.0,7.0,7.0,4.0,3.0
Bed Bugs,4.0,1.0,3.0,4.0,2.0,1.0,3.0,3.0,3.0,3.0,8.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Walk-In Service Inquiry,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Work Hours-Loud Noise Complaints,7.0,10.0,4.0,5.0,12.0,13.0,17.0,19.0,18.0,24.0,14.0,5.0
Work w/out Permit,52.0,28.0,43.0,71.0,58.0,40.0,38.0,36.0,24.0,69.0,69.0,71.0
Working Beyond Hours,44.0,29.0,39.0,52.0,52.0,37.0,25.0,25.0,32.0,42.0,61.0,55.0
Zoning,2.0,2.0,0.0,2.0,0.0,0.0,0.0,4.0,0.0,3.0,4.0,4.0