### For Data Exploration - Just change target col to get subset

In [1]:
TARGET_COL = "type"

In [2]:
from api311 import Year

old = Year("data/cleaned2015.csv")
new = Year("data/cleaned2025.csv")
old.make_points()
new.make_points()

old_summary_dct = old.summarize(TARGET_COL)
new_summary_dct = new.summarize(TARGET_COL)

/Users/ian/Desktop/MAINFRAME/School/Year 3/Year3Sem2/DS4200/DS4200_GroupProject/api311.py:11: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  self.data = pd.read_csv(fp)

In [3]:
old_monthly_data = old_summary_dct["monthly"]
new_monthly_data = new_summary_dct["monthly"]

In [4]:
old_monthly_data.head()

,January,February,March,April,May,June,July,August,September,October,November,December
type,,,,,,,,,,,,
Abandoned Building,5.0,2.0,9.0,19.0,14.0,18.0,15.0,21.0,23.0,12.0,10.0,4.0
Automotive Noise Disturbance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
BWSC General Request,19.0,9.0,11.0,12.0,19.0,12.0,12.0,35.0,32.0,19.0,10.0,12.0
BWSC Pothole,1.0,4.0,3.0,2.0,5.0,4.0,3.0,5.0,2.0,1.0,0.0,0.0
Bed Bugs,4.0,2.0,36.0,6.0,8.0,17.0,17.0,31.0,14.0,11.0,8.0,10.0

In [5]:
new_monthly_data.head()

,January,February,March,April,May,June,July,August,September,October,November,December
type,,,,,,,,,,,,
Abandoned Building,0.0,0.0,1.0,3.0,11.0,9.0,13.0,10.0,7.0,7.0,6.0,4.0
Automotive Noise Disturbance,3.0,1.0,3.0,6.0,1.0,0.0,2.0,0.0,2.0,0.0,3.0,0.0
BWSC General Request,25.0,27.0,20.0,13.0,21.0,15.0,35.0,22.0,29.0,35.0,32.0,31.0
BWSC Pothole,1.0,7.0,12.0,17.0,10.0,7.0,7.0,8.0,7.0,7.0,4.0,3.0
Bed Bugs,4.0,1.0,3.0,4.0,2.0,1.0,3.0,3.0,3.0,3.0,8.0,3.0